evento_django_project/Project/Project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns= [
    path('admin/', admin.site.urls),
    path('', include('StaticMediaPages.urls', namespace='staticmediapages'))
] 

if settings.DEBUG:
    #Below files will only served in development
    urlpatterns+=(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))
    urlpatterns+=(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))

evento_django_project/Project/StaticMediaPages/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import render_test_view,HomeCreateView,CreateEventFormView,EventManagementCreateView,ContactUsView
app_name = 'StaticMediaPages'

urlpatterns = [
    path('', HomeCreateView.as_view(), name='home'),
    path('', CreateEventFormView.as_view(), name='create_event'),
    path('event_management', EventManagementCreateView.as_view(), name='event_management'),
    path('contact_us', ContactUsView.as_view(), name='contact_us'),
]

evento_django_project/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>EstateAgency Bootstrap Template</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="{% static "img/favicon.png" %}" rel="icon">
  <link href="img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" rel="stylesheet">

  <!-- Bootstrap CSS File -->
  <link href="{% static "lib/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

  <!-- Libraries CSS Files -->
  <link href="{% static "lib/font-awesome/css/font-awesome.min.css" %}" rel="stylesheet">
  <link href="{% static "lib/animate/animate.min.css" %}" rel="stylesheet">
  <link href="{% static "lib/ionicons/css/ionicons.min.css" %}" rel="stylesheet">
  <link href="{% static "lib/owlcarousel/assets/owl.carousel.min.css" %}" rel="stylesheet">
  <link href="{% static "lib/imagehover/imagehover.min.css" %}" rel="stylesheet">

  <!-- Main Stylesheet File -->
  <link href="{% static "css/style.css" %}" rel="stylesheet">

  <!-- =======================================================
    Theme Name: EstateAgency
    Theme URL: https://bootstrapmade.com/real-estate-agency-bootstrap-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
</head>

<body data-spy="scroll" data-offset="500" data-target="#navbarc">

  <div class="click-closed"></div>
  <!--/ Create event form /-->

  {% if "/contact_us" not in request.get_full_path %}
  {% include "create_event_form.html"%} 
  {% endif %}

  <!--/ Create form End /-->

  <!--/ Nav Star /-->
  <nav id="navbarc" class="navbar navbar-default navbar-trans navbar-expand-lg fixed-top">
    <div class="container">
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarDefault"
        aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <a class="navbar-brand text-brand" href=""><!-- Logo here -->LOGO</span></a>
      <button type="button" class="btn btn-link nav-search navbar-toggle-box-collapse d-md-none" data-toggle="collapse"
        data-target="#navbarTogglerDemo01" aria-expanded="false">
        <span class="fa fa-search" aria-hidden="true"></span>
      </button>
      <div class="navbar-collapse collapse justify-content-center" id="navbarDefault">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'staticmediapages:home' %}">Home</a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Event management
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'staticmediapages:event_management' %}#corporate_event">Corporate events</a>
              <a class="dropdown-item" href="{% url 'staticmediapages:event_management' %}#wedding_planner">Wedding planner</a>
              <a class="dropdown-item" href="{% url 'staticmediapages:event_management' %}#social_events">Social events</a>
            </div>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="our_events_evento.html">Our events</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'staticmediapages:contact_us' %}">Contact us</a>
          </li>
        </ul>
      </div>

      
        {% if "/contact_us" not in request.get_full_path %}
              <button type="button" class="btn btn-b-n btn-outline navbar-toggle-box-collapse d-none d-md-block" data-toggle="collapse"
        data-target="#navbarTogglerDemo01" aria-expanded="false">
        <span class="" aria-hidden="true"> Create event</span>
      </button>
        {% endif %}

    </div>
  </nav>
  <!--/ Nav End /-->



{% block content %}

{% endblock %}



  <!--/ footer Star /-->
  <section class="section-footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-4">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">LOGO</h3>
            </div>
            <div class="w-body-a">
              <p class="w-text-a color-text-a">
                Enim minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip exea commodo consequat duis
                sed aute irure.
              </p>
            </div>
            <div class="w-footer-a">
              <ul class="list-unstyled">
                <li class="color-a">
                  <span class="color-text-a">Phone .</span> contact@example.com</li>
                <li class="color-a">
                  <span class="color-text-a">Email .</span> +54 356 945234</li>
              </ul>
            </div>
          </div>
        </div>
        
       <div class="col-sm-12 col-md-4 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">Sitemap</h3>
            </div>
            <div class="w-body-a">
              <div class="w-body-a">
                <ul class="list-unstyled">
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> <a href="{% url 'staticmediapages:home' %}">Home</a>
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> <a href="{% url 'staticmediapages:event_management' %}">Event Management</a>
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> <a href="#">Our events</a>
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> <a href="{% url 'staticmediapages:contact_us' %}">Contact us</a>
                  </li>
                  <li class="item-list-a">
                    <i class="fa fa-angle-right"></i> <a href="#">Privacy Policy</a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-12 col-md-4 section-md-t3">
          <div class="widget-a">
            <div class="w-header-a">
              <h3 class="w-title-a text-brand">Find us</h3>
            </div>

            <div class="socials-a w-body-a">
              <ul class="">
                <li class="list-inline-item">
                  <a href="#">
                    <i class="fa fa-facebook fa-lg" aria-hidden="true"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="#">
                    <i class="fa fa-twitter fa-lg" aria-hidden="true"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="#">
                    <i class="fa fa-instagram fa-lg" aria-hidden="true"></i>
                  </a>
                </li>
              </ul>
            </div>

          </div>
        </div>
      </div>
    </div>
  </section>
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">

          <div class="copyright-footer">
            <p class="copyright color-text-a">
              &copy; Copyright
              <span class="color-a">Evento</span> All Rights Reserved.
            </p>
          </div>
          <div class="credits">
            <!--
              All the links in the footer should remain intact.
              You can delete the links only if you purchased the pro version.
              Licensing information: https://bootstrapmade.com/license/
              Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=EstateAgency
            -->
            Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!--/ Footer End /-->


<a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
<div id="preloader"></div>

<!-- JavaScript Libraries -->
<script src="{% static "lib/jquery/jquery.min.js" %}"></script>
<script src="{% static "lib/jquery/jquery-migrate.min.js" %}"></script>
<script src="{% static "lib/jquery/jquery.easing.min.js" %}"></script>
<script src="{% static "lib/popper/popper.min.js" %}"></script>
<script src="{% static "lib/bootstrap/js/bootstrap.min.js" %}"></script>

<script src="{% static "lib/easing/easing.min.js"%}"></script>

<script src="{% static "lib/owlcarousel/owl.carousel.min.js"%}"></script>
<script src="{% static "lib/scrollreveal/scrollreveal.min.js"%}"></script>
<script src="{% static "lib/jquery/jquery.scrollTo.min.js"%}"></script>
<script src="{% static "lib/slick/slick.min.js"%}"></script>


<!-- Template Main Javascript File -->
<script src="{% static "js/main.js" %}"></script>

</body>
</html>

evento_django_project/templates/create_event_form.html
{% load crispy_forms_tags %}
<!--/ Create event form /-->

  <div class="box-collapse">
    <div class="title-box-d">
      <h3 class="title-d">Create event</h3>
    </div>
    <span class="close-box-collapse right-boxed ion-ios-close"></span>
    <div class="box-collapse-wrap form">
      
      <form class="form-a" method='POST' action="{% url "staticmediapages:create_event" %}">
        {% csrf_token %}

        <div class="row">
          <div class="col-md-6 mb-2">
            {{ form.first_name |as_crispy_field }}            
          </div>
          <div class="col-md-6 mb-2">
             {{ form.last_name |as_crispy_field }}
           </div>
           <div class="col-md-12 mb-2">
             {{ form.email |as_crispy_field }}
           </div>
           <div class="col-md-12 mb-2">
             {{ form.contact_no |as_crispy_field }}
           </div>
           <div class="col-md-12 mb-2">
              {{ form.category |as_crispy_field }}
           </div>
           <div class="col-md-12 mb-2">
             {{ form.company_name |as_crispy_field }}
           </div>
           <div class="col-md-12 mb-2">
             {{ form.date |as_crispy_field }}
           </div>
           <div class="col-md-12 mb-2">
             {{ form.event_description |as_crispy_field }}
           </div>
          </div>
          <div class="col-md-12">
            <button type="submit" class="btn btn-b">Create event</button>
          </div>
        </div>
      </form> 

    </div>
  </div>
  <!--/ Create form End /-->